# Generated by Django 5.1.1 on 2026-09-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RotaWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rota_weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='RotaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rota_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rota_assignments', to='core.employee')),
                ('replaced_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_assignments', to='core.rotaassignment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_assignments', to='core.site')),
                ('rota_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.rotaweek')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.shifttype')),
            ],
            options={
                'ordering': ['work_date', 'shift_type__start_time', 'site__name', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('rota_week', 'work_date', 'shift_type', 'site', 'employee'), name='unique_rota_employee_slot')],
            },
        ),
    ]
