# Generated by Django 5.1.1 on 2026-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_dailyoperation_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee-documents/%Y/%m/'),
        ),
    ]
