# Generated by Django 5.1.1 on 2026-09-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailyarrivalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_confirmations', to='core.employee')),
                ('rota_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='core.rotaweek')),
            ],
            options={
                'ordering': ['status', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('rota_week', 'employee'), name='unique_rota_employee_confirmation')],
            },
        ),
    ]
