# Generated by Django 5.1.1 on 2026-09-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employeeportalinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftAttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOK_ON', 'Book On'), ('HOURLY', 'Hourly check-in'), ('BOOK_OFF', 'Book Off')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('photo', models.FileField(upload_to='shift-attendance/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('location_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('OUTSIDE_SITE', 'Outside site'), ('LOCATION_UNVERIFIED', 'Location unverified')], default='LOCATION_UNVERIFIED', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_attendance_events', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='core.dailyoperation')),
            ],
            options={
                'ordering': ['captured_at'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'event_type', 'sequence'), name='unique_shift_attendance_event')],
            },
        ),
    ]
