# Generated by Django 5.1.1 on 2026-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_site_geofence_radius_m_site_latitude_site_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_sites',
            field=models.ManyToManyField(blank=True, related_name='manager_profiles', to='core.site'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('RECEPTIONIST', 'Receptionist'), ('EMPLOYEE', 'Guard')], default='RECEPTIONIST', max_length=20),
        ),
    ]
