# Generated by Django 5.1.1 on 2026-10-03 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_managed_sites_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('RECEPTIONIST', 'Receptionist'), ('EMPLOYEE', 'Guard'), ('CLIENT_ADMIN', 'Client Admin')], default='RECEPTIONIST', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.client'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='core.client'),
        ),
        migrations.CreateModel(
            name='ClientArrivalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='client-arrival-reports/%Y/%m/')),
                ('scheduled_count', models.PositiveIntegerField(default=0)),
                ('reached_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('not_reached_count', models.PositiveIntegerField(default=0)),
                ('unassigned_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_reports', to='core.client')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_client_arrival_reports', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_arrival_reports', to='core.shifttype')),
            ],
            options={
                'ordering': ['-report_date', 'shift_type__start_time'],
                'constraints': [models.UniqueConstraint(fields=('client', 'report_date', 'shift_type'), name='unique_client_arrival_report_shift')],
            },
        ),
    ]
